USER_LANG = {}

STRINGS = {
    "en": {
        "btn_miniapp": "🚀 ᴏᴘᴇɴ ᴍɪɴɪ ᴀᴘᴘ",
        "btn_wallet": "💼 ᴍʏ ᴡᴀʟʟᴇᴛ",
        "btn_account": "👤 ᴍʏ ᴀᴄᴄᴏᴜɴᴛ",
        "btn_search": "🔎 sᴇᴀʀᴄʜ sᴛᴏʀʏ",
        "btn_pocket": "📻 ᴘᴏᴄᴋᴇᴛ ғᴍ",
        "btn_pratilipi": "📚 ᴘʀᴀᴛɪʟɪᴘɪ ғᴍ",
        "btn_updates": "📢 ᴜᴘᴅᴀᴛᴇs ᴄʜᴀɴɴᴇʟ",
        "btn_support": "📞 sᴜᴘᴘᴏʀᴛ",
        "btn_lang": "🌐 Change Language",
        "choose_language": "<b>Choose your preferred language / अपनी भाषा चुनें:</b>",
        "lang_saved_msg": "✅ <b>Language set to English!</b>",
        "lang_updated_alert": "Language updated to English!",
        "btn_cleanchat": "🧹 ᴄʟᴇᴀɴ / ᴅᴇʟᴇᴛᴇ ᴀʟʟ ғɪʟᴇs",
        "fetching_files": "⏳ <b>ғᴇᴛᴄʜɪɴɢ ғɪʟᴇs {range_text}...</b>\n<i>ᴘʟᴇᴀsᴇ ᴡᴀɪᴛ...</i>",
        "files_delivered": "🎉 <b>ғɪʟᴇs ᴅᴇʟɪᴠᴇʀᴇᴅ sᴜᴄᴄᴇssғᴜʟʟʏ!</b> {range_text}\n\n📖 <b>sᴛᴏʀʏ:</b> {title}\n📦 <b>ᴅᴇʟɪᴠᴇʀᴇᴅ:</b> {success} / {total} Files\n\n👇 <i>Click button below to clean chat after listening:</i>",
        "btn_demo": "🎬 ᴅᴇᴍᴏ / ᴘʀᴇᴠɪᴇᴡ",
        "btn_direct_pay": "💳 ᴅɪʀᴇᴄᴛ ᴘᴀʏ (₹{price})",
        "btn_wallet_pay": "👛 ᴘᴀʏ ᴠɪᴀ ᴡᴀʟʟᴇᴛ (Bal: ₹{bal})",
        "btn_get_files_unlocked": "📂 ɢᴇᴛ ғɪʟᴇs (Unlocked)",
        "order_initiated_card": "🛒 <b>ᴏʀᴅᴇʀ ɪɴɪᴛɪᴀᴛᴇᴅ ғʀᴏᴍ ᴍɪɴɪ ᴀᴘᴘ</b>\n\n📖 <b>ᴛɪᴛʟᴇ:</b> {title}\n💰 <b>ᴘʀɪᴄᴇ:</b> ₹{price}\n👛 <b>ʏᴏᴜʀ ᴡᴀʟʟᴇᴛ:</b> ₹{bal}\n📝 <b>ᴅᴇsᴄ:</b> {desc}\n\n👇 <b>Select payment method to complete purchase:</b>",
        "story_details_card": "📖 <b>ᴛɪᴛʟᴇ:</b> {title}\n💰 <b>ᴘʀɪᴄᴇ:</b> ₹{price}\n👛 <b>ʏᴏᴜʀ ᴡᴀʟʟᴇᴛ:</b> ₹{bal}\n📝 <b>ᴅᴇsᴄ:</b> {desc}\n\n<i>👇 Choose an option below to view or purchase:</i>",
        "purchase_success_msg": "✅ <b>ᴘᴜʀᴄʜᴀsᴇ sᴜᴄᴄᴇssғᴜʟ!</b>\n\n📖 <b>sᴛᴏʀʏ:</b> {title}\n💸 <b>ᴅᴇᴅᴜᴄᴛᴇᴅ:</b> ₹{price}\n👛 <b>ʀᴇᴍᴀɪɴɪɴɢ ʙᴀʟᴀɴᴄᴇ:</b> ₹{bal}\n\n👇 Click below to access your story files:",
        "purchase_success_alert": "🎉 Purchase successful! Story unlocked.",
        "insufficient_balance_alert": "❌ Insufficient Balance!\nRequired: ₹{price}\nAvailable: ₹{bal}\n\nPlease top-up your wallet.",
        "story_not_found": "❌ <b>sᴛᴏʀʏ ɴᴏᴛ ғᴏᴜɴᴅ.</b>",
        "no_desc": "ɴᴏ ᴅᴇsᴄʀɪᴘᴛɪᴏɴ ᴀᴠᴀɪʟᴀʙʟᴇ.",
        "demo_not_available": "⚠️ Demo is not available for this story!",
        "no_demo_files": "❌ No Demo files available!",
        "sending_demo_alert": "🎬 Sending Demo files... Please check your chat!",
        "demo_header": "🎬 <b>ᴅᴇᴍᴏ / ᴘʀᴇᴠɪᴇᴡ ғᴏʀ:</b> <code>{title}</code>\n\n⏰ <i>This demo preview will automatically delete in 10 minutes!</i>",
        "welcome_msg": "<b>━━━━━━━━━━━━━━━━━━━━━━</b>\n🌟 <b>STORY SELLER BOT</b> 🌟\n<b>━━━━━━━━━━━━━━━━━━━━━━</b>\n\n<b>HELLO {name}! 👋</b>\n\n<b>USE THE BUTTONS BELOW TO SEARCH OR PURCHASE YOUR FAVORITE STORIES.</b>"
    },
    "hi": {
        "btn_miniapp": "🚀 मिनी ऐप खोलें",
        "btn_wallet": "💼 मेरा वॉलेट",
        "btn_account": "👤 मेरा खाता",
        "btn_search": "🔎 स्टोरी खोजें",
        "btn_pocket": "📻 पॉकेट एफएम",
        "btn_pratilipi": "📚 प्रतिलिपि एफएम",
        "btn_updates": "📢 अपडेट्स चैनल",
        "btn_support": "📞 सहायता",
        "btn_lang": "🌐 भाषा बदलें",
        "choose_language": "<b>अपनी पसंदीदा भाषा चुनें / Choose your preferred language:</b>",
        "lang_saved_msg": "✅ <b>भाषा हिंदी सेट हो गई है!</b>",
        "lang_updated_alert": "भाषा हिंदी में बदल दी गई है!",
        "btn_cleanchat": "🧹 चैट साफ़ करें / डिलीट करें",
        "fetching_files": "⏳ <b>फाइलें लाई जा रही हैं {range_text}...</b>\n<i>कृपया प्रतीक्षा करें...</i>",
        "files_delivered": "🎉 <b>फाइलें सफलतापूर्वक भेज दी गईं!</b> {range_text}\n\n📖 <b>स्टोरी:</b> {title}\n📦 <b>भेजी गईं:</b> {success} / {total} फाइलें\n\n👇 <i>सुनने के बाद चैट साफ़ करने के लिए नीचे बटन पर क्लिक करें:</i>",
        "btn_demo": "🎬 डेमो / झलक देखें",
        "btn_direct_pay": "💳 सीधा भुगतान (₹{price})",
        "btn_wallet_pay": "👛 वॉलेट से भुगतान (शेष: ₹{bal})",
        "btn_get_files_unlocked": "📂 फाइलें प्राप्त करें (अनलॉक)",
        "order_initiated_card": "🛒 <b>मिनी ऐप से ऑर्डर शुरू किया गया</b>\n\n📖 <b>शीर्षक:</b> {title}\n💰 <b>कीमत:</b> ₹{price}\n👛 <b>आपका वॉलेट:</b> ₹{bal}\n📝 <b>विवरण:</b> {desc}\n\n👇 <b>खरीद पूरी करने के लिए भुगतान विधि चुनें:</b>",
        "story_details_card": "📖 <b>शीर्षक:</b> {title}\n💰 <b>कीमत:</b> ₹{price}\n👛 <b>आपका वॉलेट:</b> ₹{bal}\n📝 <b>विवरण:</b> {desc}\n\n<i>👇 देखने या खरीदने के लिए नीचे दिए गए विकल्प को चुनें:</i>",
        "purchase_success_msg": "✅ <b>खरीद सफ़ल रही!</b>\n\n📖 <b>स्टोरी:</b> {title}\n💸 <b>काटे गए पैसे:</b> ₹{price}\n👛 <b>शेष वॉलेट बैलेंस:</b> ₹{bal}\n\n👇 अपनी स्टोरी फाइलों तक पहुँचने के लिए नीचे क्लिक करें:",
        "purchase_success_alert": "🎉 खरीद सफल रही! स्टोरी अनलॉक हो गई है।",
        "insufficient_balance_alert": "❌ अपर्याप्त बैलेंस!\nआवश्यक: ₹{price}\nउपलब्ध: ₹{bal}\n\nकृपया अपना वॉलेट रीचार्ज करें।",
        "story_not_found": "❌ <b>स्टोरी नहीं मिली।</b>",
        "no_desc": "कोई विवरण उपलब्ध नहीं है।",
        "demo_not_available": "⚠️ इस स्टोरी के लिए डेमो उपलब्ध नहीं है!",
        "no_demo_files": "❌ कोई डेमो फाइलें उपलब्ध नहीं हैं!",
        "sending_demo_alert": "🎬 डेमो फाइलें भेजी जा रही हैं... कृपया अपना चैट देखें!",
        "demo_header": "🎬 <b>डेमो / झलक:</b> <code>{title}</code>\n\n⏰ <i>यह डेमो 10 मिनट में अपने आप डिलीट हो जाएगा!</i>",
        "welcome_msg": "<b>━━━━━━━━━━━━━━━━━━━━━━</b>\n🌟 <b>स्टोरी सेलर बॉट</b> 🌟\n<b>━━━━━━━━━━━━━━━━━━━━━━</b>\n\n<b>नमस्ते {name}! 👋</b>\n\n<b>अपनी पसंदीदा कहानियां खोजने या खरीदने के लिए नीचे दिए गए बटनों का उपयोग करें।</b>"
    }
}

def get_text(user_id: int, key: str) -> str:
    lang = USER_LANG.get(user_id, "en")
    return STRINGS.get(lang, STRINGS["en"]).get(key, key)
